Dockerfile, Dockerfile.test, cdflow_commands/config.py, cdflow_commands/release.py, cdflow_commands/terragrunt.py, test/test_cli.py, test/test_config.py, test/test_deploy.py, test/test_release.py
We're currently running Python 2 but that's end-of-life in 2020 so let's get the drop on that and move to Python 3 while we still have the chance.
=> Migrate to Python 3

cdflow_commands/terragrunt.py, test/test_deploy.py
Where an environment specific config file exists at the conventional
location (config/<env-name>.json), include it in the terraform
parameters. This allows teams to include environment specific
configuration for their services in this file.
=> PLAT-801 - Add config var file

cdflow_commands/cli.py, cdflow_commands/config.py, test/test_config.py
We added a git remote error class with message to make it easier for a
user to know that they have to setup a remote. We use this to infer
component name.
=> Added GitError class.

cdflow_commands/cli.py, cdflow_commands/deploy.py, cdflow_commands/destroy.py, cdflow_commands/terragrunt.py, test/test_cli.py, test/test_deploy.py, test/test_destroy.py, tf-destroy/main.tf
The only things that are needed (and should be needed) for a destroy
are the tfstate file and the AWS region. This change refactors destroy
to just use those.
JIRA: PLAT-820
=> Simplify terraform detstroy

cdflow_commands/cli.py, cdflow_commands/destroy.py, test/test_destroy.py
So that we don't think a service exists because the (empty) tfstate
file is hanging around.
JIRA: PLAT-820
=> Remove tfstate file from s3 after destroy

cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/deploy.py, cdflow_commands/destroy.py, cdflow_commands/ecs_monitor.py, cdflow_commands/logger.py, test/test_cli.py, test/test_config.py, test/test_deploy.py, test/test_destroy.py, test/test_ecs_monitor.py
Once Terraform has completed the changes to the infrastructure we'd like to get feedback for the user as to whether the new version of the service is running.
This adds in logic to query ECS for the running service and checks that the desired number of instances of the requested version are running.
Example output:
```
[terragrunt] 2017/03/06 16:59:16 Lock released!
[2017-03-06 17:00:17] Deploying ECS tasks - desired: 2 pending: 0 running: 0 previous: 2
[2017-03-06 17:00:32] Deploying ECS tasks - desired: 2 pending: 0 running: 0 previous: 2
[2017-03-06 17:00:47] Deploying ECS tasks - desired: 2 pending: 0 running: 2 previous: 2
[2017-03-06 17:01:02] Deploying ECS tasks - desired: 2 pending: 0 running: 2 previous: 2
[2017-03-06 17:01:17] Deploying ECS tasks - desired: 2 pending: 0 running: …
```
=> PLAT-803 - monitor ecs deployment

cdflow_commands/cli.py, test/test_cli.py
This adds a `--verbose` flag which toggles the display of debug
messages on the command line for degbugging purposes.
JIRA: PLAT-837
=> Adds the ability to display debug messages

cdflow_commands/cli.py, test/test_cli.py
We want to make sure that in a shell environment the program won't
continue to run when e.g. the deployment times out.
This prints the exception to the error log and exits with status 1
when a `UserError` is caught.
JIRA: PLAT-843
=> Makes the program exit with status 1 on error

cdflow_commands/config.py, test/test_cli.py, test/test_config.py
We've removed the indirection with loading the ECS cluster name from
the config so this logic doesn't apply, and indeed causes failures
when using the latest version of the config.
JIRA: PLAT-846
=> Removes logic which loads cluster name from config

cdflow_commands/ecs_monitor.py, test/test_cli.py, test/test_ecs_monitor.py
During the deploy we'd like to see the ECS server events feed to help us with eventual healthiness problems of tasks.  If cdflow detects any tasks failed health check, deploy should fail immediately.
[1] Example output of successful deploy after this PR
[2] Example output of failed deploy due to failed task health check (after this PR)
[1]
```
State path: .terraform/terraform.tfstate
[terragrunt] 2017/03/10 15:20:37 Attempting to release lock for state file aslive-grahamlyons-test in DynamoDB
[terragrunt] 2017/03/10 15:20:37 Lock released!
[2017-03-10 15:20:38] ECS service tasks - desired: 2 pending: 0 running: 0 previous: 2
[2017-03-10 15:20:53] ECS service event - (service aslive-grahamlyons-test) has started 2 tasks: (task c66a16ed-40a9-4f1c-be05-9f69365ce2bb) (task …
```
=> PLAT-826 - Monitor task healthiness during the deploy & fail if any of the tasks failed

cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/ecs_monitor.py, cdflow_commands/exceptions.py, test/test_cli.py, test/test_ecs_monitor.py
We had only a `UserError` as an exception parent, which was meant for
exceptions to be displayed to the user. It used a fixed string message
which wasn't always appropriate.
This introduces a `CDFlowError` at the top level and has `UserFacingError`
and `FixedMessageError` inheriting from that - `UserFacingFixedMessageError`
inherits from both of those:
```
CDFlowError
|
UserFacingError             FixedMessageError
\          /
UserFacingFixedMessageError
```
JIRA: PLAT-848
=> Reworks the exception hierarchy for the project

cdflow_commands/ecs_monitor.py, test/test_ecs_monitor.py
Previously, deploy would always succeed when we were deploying a new service, even, if the new server would go into unhealthy state right after.  This was happening due to lack of previously running tasks during deploy for new service and deployment finished condition was being met as soon as running tasks number equaled desired tasks number.
This PR introduces additional wait time (healthcheck grace period time) which is executed when we're deploying a new service.
=> PLAT-836 - Deploy always completes when deploying a new service

cdflow_commands/config.py, test/test_config.py
What?
-----
If the git repository setup as remote url contains a trailing url,
cdflow would fail extracting the component name.
To fix it, we must also trim the `/`
How to test?
------------
A test has been added, run `./test.sh`
Who?
----
Anyone but @keymon
=> Fix not able to get component name with trailing /

cdflow_commands/config.py, cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_release.py
Some users would like to be able to run tests against their packaged
application before it's pushed up the the repo.
This adds a hook to an `on-docker-build` script which is run and
passed the newly built image as an argument.
=> Call a script post-build to verify the image

cdflow_commands/config.py, test/test_config.py
https://workflow.mergermarket.com/browse/PLAT-865
What?
----
As platform engineer I want to make the missing metadata errors in CDFlow
more user friendly, eg. if we don't specify REGION in service.json,
I want to see a user-friendly message like
"Deployment failed - did you set REGION in service.json?"
How to review?
--------------
Code review. Run the test with: `./test.sh -k test_service_metadata_user_facing_error`
Who?
----
Anyone but @keymon
PLAT-865
=> [PLAT-865] More friendly message for incomplete service.json

cdflow_commands/plugins/infrastructure.py, test/plugins/test_infrastructure_deploy.py
When using infrastructure only projects, we still want to include environment specific configs (we seem to have forgot about it when adding infrastructure plugin)
=> Include environment config for infrastructure

cdflow_commands/exceptions.py, cdflow_commands/plugins/ecs.py, cdflow_commands/plugins/infrastructure.py, test/plugins/test_ecs.py, test/plugins/test_infrastructure.py
We want CDFlow to throw an exception and fail a deployment as soon as any of the required arguments is missing.
We implement it within plugins, as different plugins have different arguments required to work (eg. version is needed by ECS deploy but not by infrastructure)
JIRA: PLAT-887
=> Throw exception when required arguments are missing

Dockerfile, Dockerfile.test
The Debian-based Python image is more than twice as large as the one based on Alpine Linux so it would be nicer for users not to wait so long to pull our image down.
=> Update container to run Alpine Linux

cdflow_commands/plugins/aws_lambda.py, cdflow_commands/state.py
When we run a release of a lambda project, we do a lot of work in the
background that isn't really exposed to the user so they get no feedback
when things go as expected. We've added logging to show whats going on
including some debug messages around the s3 bucket creation and tagging.
JIRA:PLAT-924
=> Adding logging around the release of Lambda

cdflow_commands/plugins/aws_lambda.py
If you have a top level directory in the zip file with the lambda
function in it, you can't edit the function in line on the aws console.
Here we're zipping the lambda handler file directly to the top level.
JIRA: PLAT-915
=> Changing the way we zip up the lambda

cdflow_commands/cli.py, cdflow_commands/plugins/aws_lambda.py, cdflow_commands/plugins/base.py, cdflow_commands/plugins/ecs.py, cdflow_commands/plugins/infrastructure.py, test/plugins/test_base_destroy.py, test/plugins/test_infrastructure_deploy.py, test/plugins/test_lambda_deploy.py, test/test_integration_cli_infrastructure.py, test/test_integration_cli_lambda.py
When we change infrastructure we might want to plan first without
calling apply immediately. This flag will stop apply from being run.
Early feedback would be appreciated as this is an interface change. Also good to get feedback on the use of `call_args_list` as it tests what I want but there could be a prettier way?
```
terraform_calls = check_call.call_args_list
+        assert len(terraform_calls) < TERRAFORM_FULL_LIFECYCLE_CALL_COUNT
+        assert (
+            (
+                ['terraform', 'plan'] + ignored_parameters + ['infra'],
+            ), ANY
+        ) in terraform_calls
+        assert (
+            (
+                ['terraform', 'apply'] + ignored_parameters + ['infra'],
+            ), ANY
+        ) not in terraform_calls
+
```
JIRA: PLAN-958
=> Added plan flag for infrastructure deploy

cdflow_commands/cli.py, cdflow_commands/exceptions.py, test/test_cli.py
We want to throw friendly exception when unsupported project type is specified in `service.json`
JIRA: PLAT-969
=> Throw friendly exception for unsupported project

cdflow_commands/deploy.py, test/test_deploy.py, test/test_integration_cli.py
Using the wrapper if terraform asks for input then you see the prompt
being generated continuously without the opportunity to input.
JIRA: PLAT-1072
=> Stop terraform asking for input

Dockerfile, cdflow_commands/state.py
Starting with Terraform 0.10, Terraform Providers will be split into separate repositories hence being a separate to Terraform core itself entities.
Default Terraform behaviour will be downloading latest versions of providers available; given this default behaviour, few more points to considerate:
1). We can "pin" specific versions of Terraform Providers using .terraformrc file
2). These will be hosted on Github making Github a potential dependency for making new cdflow-commands releases
3). At the moment there's not way to use unreleased Terraform Providers - use-case here being when we've got a buggy provider, or provider which is missing feature - we do the work to bring it up to our requirements but are unable to use it until a new version of provider is available.
Given this, I've …
=> Switch Terraform to use individual providers && update Terraform to 0.10

cdflow_commands/state.py, test/test_integration_cli.py, test/test_state.py
We need to use the assumed role credentials to perform Terraform init - otherwise it'll fail when trying to download the statefile.
=> Use assumed role credentials for Terraform init

README.md, cdflow_commands/cli.py
This change removes the name CDFlow Commands, as well as spelling
cdflow in lowercase (CDFlow looks a bit klunky to me). This is in
preparation for proposing we rename this repo to cdflow-docker-image to
more directly describe its purpose. It also includes more wording that
describes this repo's relationship with the cdflow repo.
=> Improve messaging

cdflow_commands/config.py, cdflow_commands/deploy.py, cdflow_commands/destroy.py, cdflow_commands/state.py, test/test_config.py, test/test_deploy.py, test/test_destroy.py, test/test_integration_cli.py
This change makes sure AWS_DEFAULT_REGION is set for all terraform
calls.
JIRA: PLAT-1073
=> Dry out terraform env and add region

cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_release.py
check_call needs an absolute path, so this was failing.
=> Use absolute path for on-docker-build

Dockerfile
We'd like to be able to rely on data source for Logentries LogSets - there's a pending PR open on the Logentries Provider and until it's merged, we need to use in-house baked version of the provider.
=> Add in-house-baked Terraform Logentries Provider

.gitignore, cdflow_commands/deploy.py, cdflow_commands/destroy.py, cdflow_commands/process.py, cdflow_commands/release.py, cdflow_commands/state.py, test/test_process.py
PLAT-1083
Output sample:
```
Downloading modules...
Get: git::https://github.com/mergermarket/tf_ecs_service_infrastructure.git
Get: git::https://github.com/mergermarket/tf_route53_dns.git
Get: git::https://github.com/mergermarket/tf_alb_listener_rules.git
Get: git::https://github.com/mergermarket/tf_ecs_update_monitor.git
Get: git::https://github.com/mergermarket/tf_load_balanced_ecs_service.git
Get: git::https://github.com/mergermarket/tf_ecs_task_definition.git
Get: git::https://github.com/mergermarket/tf_ecs_container_definition.git
Initializing the backend...
"lock_table": [DEPRECATED] please use the dynamodb_table attribute
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider …
```
=> Stop showing python stacktrace when terraform operations fail

cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_release.py, test/test_integration_cli_ecs.py
When a release is build and pushed to ecr we also want to tag it with
the "latest" tag. We use this tag for the docker `--build-cache` command which has been added to all the docker builds.
JIRA: PLAT-998
=> Added tag latest to release built with cdflow & use --cache-from command when building

cdflow_commands/cli.py, cdflow_commands/config.py, test/test_config.py, test/test_integration_cli.py, test/test_integration_cli_ecs.py, test/test_integration_cli_infrastructure.py, test/test_integration_cli_lambda.py
Fetch the role session name from STS - there's little value in fetching the role name from the environment so we may as well fetch it from STS as that can't be overridden.
=> Plat 1081 fix role session name inconsistency

cdflow_commands/config.py, test/test_config.py, test/test_integration_cli.py, test/test_integration_cli_ecs.py, test/test_integration_cli_infrastructure.py, test/test_integration_cli_lambda.py
The user id we get back from STS might not be legal for using as the role name for a new assumed session so replace anything that is unpalatable.
=> Replace illegal characters in user id from STS

cdflow_commands/account.py, cdflow_commands/cli.py, cdflow_commands/deploy.py, cdflow_commands/release.py, test/test_account.py, test/test_cli.py, test/test_deploy.py, test/test_release.py
This lays the ground work for supporting multiple accounts in a single
deploy. It adds support for having each environment be a mapping from
account prefix to account alias, so that we can pass a mapping of
account prefixes to IAM role ARNs into the deploy.
JIRA: PLAT-1152
=> Support multiple account aliases in scheme

cdflow_commands/release.py, test/test_integration_cli_ecs.py, test/test_integration_cli_infrastructure.py, test/test_integration_cli_lambda.py, test/test_release.py
Unfortunately copytree doesn't do the equivalent of `cp -r` - if the
destination exists it fails. In order to keep the behaviour of not
including the .git folder, this change copies the individual files only.
=> Fix platform config copy

cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/state.py, test/test_cli.py, test/test_config.py, test/test_integration_cli.py, test/test_state.py
This change adds the `terraform-state-in-release-account` boolean
option on the cdflow.yml manifest. This is needed when deploying to
multiple accounts - e.g. for the login-subscriber service - but more
than that, I see it as a valuable goal to have all of our terraform
state files in a single s3 bucket so we have a central inventory of all
of the AWS infrastructure owned by Acuris. This therefore proposes that
we migrate all services to set this flag before making it the default
and removing the flag altogether. This combined with having a shared
release account would achieve the goal of putting all of the state in
one place (moving state to a new release account should a service or
group of services transfer ownership to another organisation should
also be pretty easy).
JIRA: PLAT-1152
=> Add option to store state in release account

cdflow_commands/cli.py, cdflow_commands/config.py, test/test_config.py
This is to unblock the login-subscriber. Not sure whether the long term
direction should be to migrate to this, or to move all credstash
handling into the terraform and hence keep it in the deploy account.
JIRA: PLAT-1152
=> Add option to store secrets in release account

cdflow_commands/config.py, test/test_config.py
Trying to set an environment variable to None doesn't work, so if the
session token isn't set (when it's the root account in jenkins) don't
set it.
=> Don't set session token when there isn't one

cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/state.py, test/test_cli.py, test/test_config.py, test/test_state.py
When migrating older cdflow projects to new ones and trying to run the
new pipeline with new infrastructure definition in parallel, the deploy
finds the existing tfstate file and removes all of the infrastructure
(not very helpful). This change adds an optional `tfstate-filename` key
that chnages the last part of the key we use to store the tfstate file
in s3 so that the new infrastructure can coexist with the old, until we
are ready to move it to the default location.
=> Add support for tfstate-filename manifest key

cdflow_commands/deploy.py, cdflow_commands/process.py, test.sh, test/test_deploy.py, test/test_integration_cli.py
While performing Terraform plan we want to obfuscate secret values so they're not logged into the console (and saved as part of Jenkins jobs).
JIRA: PLAT-1200
=> Stop CDFlow exposing secrets values in output

cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_release.py
The method is not found on the ECR object for some reason.
=> Stop enforcing ECR lifcycle

Dockerfile
Updating the terraform version to the latest version. Also updating the
providers and no longer pulling from the mmg plugin where it's not
needed. So the AWS proveder, for example, now pulls from the hashicorp
repo. This will just mean changing the version in the future.
Also updating to the main alpine repo as the community was throwing a dependency error.
=> Updating terraform to 0.11.0 and providers.

Dockerfile
We use this provider in the openvpn code but the build fails at the moment because it's not included in the `cdflow-commands` image.
There is a patch release of Terraform available, plus our pull request to the Fastly provider has been merged. There is also a new version of the AWS provider.
=> Add tls provider and upgrade Terraform

cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/release.py, test/test_release.py
Add in new command line option '--release-data'
Can be used 0 to many times to send in extra data to the release
Will be stored in the release.json
=> Jenkins Slave Pool

cdflow_commands/account.py, cdflow_commands/plugins/aws_lambda.py, cdflow_commands/state.py, test/plugins/test_lambda_release.py, test/test_account.py
We were trying to create buckets with the same name that we've already
created. This should solve that for each account. Now we will pull it
from the account-scheme.json. To ensure backwards compatability we set
the lambda bucket to empty if not in the account-scheme. This is to
deploy a lambda into the svcs account.
JIRA: PLAT-1325
=> Using lambda bucket name from account-scheme.json

cdflow_commands/plugins/aws_lambda.py, cdflow_commands/state.py, test/plugins/test_lambda_release.py, test/test_integration_cli_lambda.py
To be more in line with the release bucket for services we're moving the
logic of creating the bucket into the terraform inside
account-resources.
JIRA: PLAT-1325
=> Removing create bucket logic from lambda release

cdflow_commands/account.py, cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/constants.py, cdflow_commands/release.py, test/test_cli.py, test/test_config.py, test/test_integration_cli.py, test/test_release.py
Store the account scheme in the release artefact and use this for
everything beyond finding the release artefact for deploys and destroys.
This will ensure changes we make to the account scheme will be applied
as a release goes through the pipeline, rather than (potentially) being
applied first to live.
JIRA: PLAT-1420
=> Persist account scheme through the pipeline

cdflow_commands/account.py, cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/plugins/aws_lambda.py, cdflow_commands/release.py, test/plugins/test_lambda_release.py, test/test_account.py, test/test_config.py, test/test_release.py
In order to provision lambdas in multiple regions, the release zip needs
to uploaded to a bucket in each region. This change adds a
`multi-region` flag to the `cdflow.yml` manifest that causes the lambda
plugin to upload the zip to a set of buckets configured in the account
scheme. It then provides details of these buckets in the release
metadata passed to terraform.
=> Support multi-region lambdas

cdflow_commands/cli.py, test/test_cli.py
We were going to put this in the release account, but since have decided
to deprecate credstash in favour of secrets manager in the deploy
account. This behaviour involves the minimum of work before we are able
to remove this code (in particular no need to migrate credstash secrets
when moving components to the new account schemes.
=> Deploy account for secrets in new account schemes

cdflow_commands/cli.py, cdflow_commands/state.py, test/test_integration_cli.py
Removing the state causes a problem with the hash of the state in DynamoDB, which we don't remove. As we don't own this we shouldn't remove it.
=> Remove the deletion of the state key on destroy

Dockerfile
This is now in version 1.0 and is maintained as an official provider, therefore it is downloaded by Terraform when it's needed.
=> Remove the manually installed acme provider

Pipfile.lock, cdflow_commands/cli.py, cdflow_commands/state.py, test/test_integration_cli.py, test/test_state.py
The key in the release account logic now contains the team because granting fine-grained access to component paths in S3 runs into IAM policy size limits.
=> Add the team to the workspace key prefix in S3

cdflow_commands/cli.py, cdflow_commands/release.py, test/test_integration_cli.py, test/test_integration_cli_ecs.py, test/test_integration_cli_infrastructure.py, test/test_integration_cli_lambda.py, test/test_release.py
The initial update I did only did it for the Terraform state bucket.
This fixes that mistake and adds the `team/` prefix to the Lambda and release bucket paths.
=> Update the paths in S3 for Lambdas and releases

cdflow_commands/cli.py, cdflow_commands/config.py, test/test_cli.py, test/test_config.py
Add the facility to use a new account scheme, pointed to by the one configured in `cdflow.yml`.
Will upgrade to the new scheme if **either**:
- team is whitelisted **OR**
- component is whitelisted
=> Forward account scheme

cdflow_commands/account.py, cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_release.py, test/test_account.py, test/test_cli.py, test/test_config.py
Introduce a `"region"` key for accounts in the account scheme. If present, a session will be created in that region instead of the `"default-region"` specified in the account scheme.
=> Region support in accounts

cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_release.py, test/test_integration_cli_ecs.py
Fails to get existing layers from previous builds causing an increase of build time when running cdflow release.
PLAT-1851
=> Removes --cache-from

cdflow_commands/config.py, test/test_config.py, test/test_integration_cli_deploy.py, test/test_integration_cli_destroy.py, test/test_integration_cli_ecs.py, test/test_integration_cli_infrastructure.py, test/test_integration_cli_lambda.py, test/test_integration_cli_shell.py
There is a session duration hard limit in AWS of 1 hour when
assuming a role when you have already assumed a role, it's
called role chaining.
=> Set session duration to 1 hour when running as an assumed role

cdflow_commands/state.py
If an S3 bucket has deny all cdflow crashes trying to check
the tags on that bucket
try/except will handle this and allow cdflow to continue
=> Add try/except to handle S3 buckets with deny_all perms
