Dockerfile
We want to avoid the bug described in
https://github.com/hashicorp/terraform/issues/14760
How to review/test?
--------------
Code review.
I have tested it with cdflow-test-service, and it is OK.
The specific issue is described with a case scenario in  https://github.com/hashicorp/terraform/issues/14760, it would be complicated create a specific regression test here.
Dependencies
------------------
After merge (reviewer or myself, this is just a reminder): 
* tag the repo to get a new container and update the dependency in https://github.com/mergermarket/cdflow/blob/master/infra/scripts/cdflow#L11
* Pull and test the change in plaftform-jira, by changing the variable CATALINA_OPTS and checking if the bug https://github.com/hashicorp/terraform/issues/14760 is still happening, ie. the …
=> [PLAT-948] Upgrade to terraform 0.9.5

cdflow_commands/cli.py, cdflow_commands/plugins/ecs.py, test/plugins/test_ecs_deploy.py, test/test_integration_cli_ecs.py
Now we can plan out an ecs-service deploy before running the apply.
JIRA: PLAN-958
=> Added plan to ecs deploy.

cdflow_commands/deploy.py, cdflow_commands/destroy.py, test/test_deploy.py, test/test_destroy.py, test/test_integration_cli.py, tf-destroy/main.tf
All the Terraform provider config is now done via the environment.
JIRA: PLAT-1073
=> Do not pass the `aws_region` parameter

.travis.yml
This will give us feedback on pull requests more easily.
=> Add a Travis config file to run tests

Jenkinsfile, cdflow_commands/release.py, test/test_release.py
This broke cdflow and somehow got through our pipeline. I am therefore
putting in a manual confirmation until we are able to figure out why
this wasn't caught.
=> Fix ignore pattern

cdflow_commands/cli.py
This doesn't make sense for multiple account deploys.
JIRA: PLAT-1152
=> Move account id check into branch

Dockerfile
We want to add the external data provider so we can use it in
https://github.com/mergermarket/tf_ecs_container_definition/commit/55c6dc3aba6ecc8bef95eb7ce104018258c1615e
=> Adding external data provider to image

Dockerfile
We'd like to automate the creation of datadog resources so we'll need this.
=> Add the datadog terraform provider

Dockerfile
This is required for confluence backups
=> Add archive provider

Dockerfile
We want to use this provider with cdflow.
=> Adding in the archive provider

Dockerfile
So we can automate github permissions.
=> Add github provider

cdflow_commands/release.py, test/test_release.py
Was trying to write a dictionary to a file without serialising it.
=> Fix saving of account scheme

cdflow_commands/account.py, cdflow_commands/cli.py, cdflow_commands/config.py, test/plugins/test_ecs_release.py, test/plugins/test_lambda_release.py, test/test_account.py, test/test_cli.py, test/test_config.py
So that we can use team specific resources.
JIRA: PLAT-1437
=> Support `{team}` placeholder in account scheme

cdflow_commands/plugins/aws_lambda.py, test/plugins/test_lambda_release.py
Easier to setup
Will work better with boilerplates
=> Allow generic source folder for lambdas

Dockerfile
=> Remove logentries provider

Dockerfile
kubectl and aws-iam-authenticator added so the aws eks module
can setup the required authentication
=> Add in execs for k8r to run

Pipfile, Pipfile.lock
These versions of moto and botocore don't cause the tests to fail.
=> Update to the latest moto, botocore and boto3

Dockerfile
This fixes team-resources state file error that was poked using version 0.11.11
=> Upgrade Terraform to version 0.11.11

cdflow_commands/cli.py, cdflow_commands/config.py, cdflow_commands/state.py, test/test_cli.py, test/test_config.py, test/test_state.py
If there is a new account scheme then find all the state for the component and move it to the release account.
=> Migrate state

cdflow_commands/cli.py, test/test_cli.py
The `--component` flag is not compatible with the using the release account because the resources, like ECR repos, are created ahead of pushing to them. Changing the component name from the repo name is not supported.
=> Don't migrate state if --component is passed

Dockerfile, cdflow_commands/plugins/aws_lambda.py, test.sh, test/plugins/test_lambda_release.py
Fix the path in S3 for the Lambda code archives in the release account.
=> Lambda s3 key fix

cdflow_commands/destroy.py
Fix when 'terraform plan -destroy -detailed-exitcode' returns the wrong exit code when no changes are present.
More info:
https://github.com/hashicorp/terraform/issues/18453
https://github.com/hashicorp/terraform/issues/18224
=> Fix 'terraform plan -destroy -detailed-exitcode'

Dockerfile, cdflow_commands/cli.py, cdflow_commands/state.py, test/test_cli.py, test/test_integration_cli_shell.py, test/test_state.py
`cdflow shell <env>` command for working on local config.
=> cdflow shell

cdflow_commands/cli.py, cdflow_commands/constants.py, cdflow_commands/deploy.py, test/test_deploy.py, test/test_integration_cli_shell.py
Start a shell inside a release bundle, with the providers, modules and config.
=> Download release and start shell

.travis.yml, Dockerfile, cdflow_commands/deploy.py, test.sh
=> Changes to use Terraform 0.12

cdflow_commands/plugins/ecs.py
If the user within the container has a .docker/config.json file in their home
directory, login to dockerhub prior to building the container
(because building the container pulls from dockerhub)
=> Fix for dockerhub pull limits problems
